#!/bin/bash

echo "🔗 Conectando ao banco PostgreSQL do Render..."
echo "📋 Dados de conexão:"
echo "   Host: dpg-d1fs2rali9vc739tpac0-a.oregon-postgres.render.com"
echo "   Database: breno_erp"
echo "   User: breno_erp_user"
echo "   Password: aHQO5rzBcecx5bRm2Xt53UQPxS49OXLj"
echo ""

echo "🚀 Tentando conectar..."
psql "postgresql://breno_erp_user:aHQO5rzBcecx5bRm2Xt53UQPxS49OXLj@dpg-d1fs2rali9vc739tpac0-a.oregon-postgres.render.com/breno_erp"

echo ""
echo "✅ Se conectou com sucesso, execute os comandos SQL:"
echo ""
echo "1. Criar tabela segments:"
echo "CREATE TABLE IF NOT EXISTS segments ("
echo "  id SERIAL PRIMARY KEY,"
echo "  name VARCHAR(255) NOT NULL,"
echo "  description TEXT,"
echo "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
echo "  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
echo ");"
echo ""
echo "2. Criar tabela users:"
echo "CREATE TABLE IF NOT EXISTS users ("
echo "  id SERIAL PRIMARY KEY,"
echo "  name VARCHAR(255) NOT NULL,"
echo "  email VARCHAR(255) UNIQUE NOT NULL,"
echo "  password VARCHAR(255) NOT NULL,"
echo "  role VARCHAR(50) DEFAULT 'user' CHECK(role IN ('user', 'admin')),"
echo "  segment_id INTEGER REFERENCES segments(id),"
echo "  status VARCHAR(50) DEFAULT 'ativo' CHECK(status IN ('ativo', 'inativo', 'bloqueado')),"
echo "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
echo "  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
echo ");"
echo ""
echo "3. Inserir segmento padrão:"
echo "INSERT INTO segments (name, description) VALUES ('Geral', 'Segmento geral do sistema');"
echo ""
echo "4. Inserir usuário admin:"
echo "INSERT INTO users (name, email, password, role, status) VALUES ('Admin ERP Pro', 'admin@erppro.com', '\$2a\$12\$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj3ZxQQxq6eq', 'admin', 'ativo');"
echo ""
echo "5. Verificar se foi criado:"
echo "SELECT * FROM users;"
echo "SELECT * FROM segments;" 